# Generated by Django 5.1.4 on 2024-12-31 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayersPGN',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player', models.TextField(help_text='Nom du joueur')),
                ('pgn_file', models.TextField(verbose_name='Nom du fichier pgn')),
                ('generated', models.BooleanField(default=False)),
            ],
        ),
    ]
