# Generated by Django 5.1.4 on 2024-12-31 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_playerspgn'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerspgn',
            name='video_file_name',
            field=models.CharField(blank=True, help_text='Nom du fichier vidéo généré', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='playerspgn',
            name='video_generation_date',
            field=models.DateTimeField(blank=True, help_text='Date de génération de la vidéo', null=True),
        ),
    ]
