# Generated by Django 5.1.4 on 2025-01-02 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_playerspgn_video_file_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerspgn',
            name='music',
            field=models.TextField(null=True, verbose_name='musique en fond'),
        ),
    ]
